### PR TITLE
Fix params block in included module

### LINKED ISSUE #6936: Providing input a typed param does not work when there is an `include` in the script that has a `params` block as well
## Bug report 
Example:

test2.nf:
```
params {
    test2_param: String = "test2"
}
process test2 {
script:
"""
echo ${params.test2_param}
"""
}
```

test1.nf:
```
include {test2} from './test2.nf'
params {
    test1_param: String = "test"
}
process test1 {
script:
"""
echo ${params.test1_param}
"""
}

workflow {
main:
test1()
}
```

Then setting test1_param:
```
nextflow run test1.nf --test1_param "hi"

 N E X T F L O W   ~  version 26.02.0-edge

Launching `test1.nf` [hungry_stone] revision: 39af0968aa

Parameter `test1_param` was specified on the command line or params file but is not declared in the script or config
```

but also neither for test2_param:

```
nextflow run test1.nf --test2_param "hi"

 N E X T F L O W   ~  version 26.02.0-edge

Launching `test1.nf` [big_raman] revision: 39af0968aa

Parameter `test2_param` was specified on the command line or params file but is not declared in the script or config
```

### Environment 

* Nextflow version: version 26.02.0

### PR DESCRIPTION
**Pull request by bentsherman**
Close #6936 

This PR fixes the behavior of `params` block in included modules.

Currently, the included `params` block is being eagerly evaluated, clobbering the params in the main script. This PR applies the same pattern from the `output` block also to the `params` block -- don't evaluate the `params` block until the script is being executed as the entrypoint

### CODE REVIEW

File: modules/nextflow/src/main/groovy/nextflow/script/ParamsDef.groovy [hunk 1]
```diff
@@ -0,0 +1,47 @@
...
+
+import groovy.transform.CompileStatic
+import groovy.util.logging.Slf4j
+import nextflow.Session
+/**
+ * Models the workflow params definition
+ *
+ * @author Ben Sherman <bentshermann@gmail.com>
+ */
+@Slf4j
```
Comment (jorgee) [inline modules/nextflow/src/main/groovy/nextflow/script/ParamsDef.groovy]: This is not required
```suggestion

```

File: modules/nextflow/src/main/groovy/nextflow/script/ParamsDef.groovy [hunk 2]
```diff
@@ -0,0 +1,47 @@
...
+ * distributed under the License is distributed on an "AS IS" BASIS,
+ * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+ * See the License for the specific language governing permissions and
+ * limitations under the License.
+ */
+
+package nextflow.script
+
+import groovy.transform.CompileStatic
+import groovy.util.logging.Slf4j
```
Comment (jorgee) [inline modules/nextflow/src/main/groovy/nextflow/script/ParamsDef.groovy]:
```suggestion

```
