### PR TITLE
Report an error on duplicate workflow name definitions

### LINKED ISSUE #4086: StackOverflowError when imported workflow has same name as native definition
## Bug report 

Initially reported via Seqera Labs support portal: https://support.seqera.io/a/tickets/3591

### Expected behavior and actual behavior

Warning should be thrown when an imported workflow name conflicts with a workflow defined within the importing file.

### Steps to reproduce the problem

Run `nextflow run main.nf -entry WORK_TWO` against the following pipeline.

main.nf
```
#!/usr/bin/env nextflow

nextflow.enable.dsl = 2

include { WORK_ONE } from './w1'
include { WORK_TWO } from './w2'
include { WORKFIVE } from './w5'

workflow WORKONE {  // works
    WORK_ONE ()
}

workflow WORK_TWO {  // StackOverflowError
    WORK_TWO ()
}

workflow WORKTHREE {  // works
    exit 0, "wf3"
}

workflow WORK_FOUR {  // works
    exit 0, "wf4"
}

workflow WORK_FIVE {  // works
    WORKFIVE ()
}

workflow {
    WORK_ONE ()
}
```

w1.nf:
```
workflow WORK_ONE {
    exit 0, "wf1"
}
```

w2.nf
```
workflow WORK_TWO {
    exit 0, "wf2"   
}
```

wf5.nf
```
workflow WORKFIVE {
    exit 0, "wf5"   
}
```

### Program output 

```bash
$ nextflow run main.nf -entry WORK_TWO
N E X T F L O W  ~  version 23.01.0-edge
Launching `main.nf` [marvelous_brattain] DSL2 - revision: 849da39fc0
Unexpected error [StackOverflowError]

 -- Check script 'main.nf' at line: 14 or see '.nextflow.log' file for more details
```

### Environment 

* Nextflow version: 23.01.0-edge, 23.04.2
* Java version: OpenJDK 64-Bit Server VM 17.0.4.1+0
* Operating system: Linux
* Bash version: GNU bash, version 5.0.17(1)-release (x86_64-pc-linux-gnu)

### PR DESCRIPTION
**Pull request by bentsherman**
Close #4086 

Consider the following pipeline script:
```groovy
// main.nf
include { WORK_ONE } from './w1'

workflow WORK_ONE {
    WORK_ONE ()
}

workflow {
    WORK_ONE ()
}
```

```groovy
// w1.nf
workflow WORK_ONE {
    exit 0, "wf1"
}
```

Currently this causes a stack overflow error:
```console
$ nextflow run gh-4086
N E X T F L O W  ~  version 23.06.0-edge
Launching `gh-4086/main.nf` [sick_williams] DSL2 - revision: c420b3da5f
ERROR ~ Unexpected error [StackOverflowError]

 -- Check script 'gh-4086/main.nf' at line: 4 or see '.nextflow.log' file for more details
```

With this PR, Nextflow will warn about the duplicate workflow name:
```console
$ ../launch.sh run gh-4086
N E X T F L O W  ~  version 23.06.0-edge
Launching `gh-4086/main.nf` [jolly_avogadro] DSL2 - revision: db2d0fa85b
WARN: A process with name 'WORK_ONE' is defined more than once in module script: /home/bent/projects/nextflow-io_nextflow/sketches/gh-4086/main.nf -- Make sure to not define a function with the same name as a workflow or process
ERROR ~ Unexpected error [StackOverflowError]

 -- Check script 'gh-4086/main.nf' at line: 4 or see '.nextflow.log' file for more details
```

And if strict mode is enabled, this warning will become an error.

### CODE REVIEW

**Comment by pditommaso** [comment]
It would be nice to add a unit test to validate this

File: modules/nextflow/src/test/groovy/nextflow/script/ScriptMetaTest.groovy [hunk 1]
```diff
@@ -172,4 +191,44 @@ class ScriptMetaTest extends Dsl2Spec {
...
+        e.message.contains "A component (function, process, or workflow) named 'func1' is defined more than once"
+
+        when:
+        meta1.addDefinition(proc1)
+        then:
+        e = thrown(DuplicateModuleFunctionException)
+        e.message.contains "A component (function, process, or workflow) named 'proc1' is defined more than once"
+
+        when:
+        meta1.addDefinition(work1)
```
Comment (pditommaso) [inline modules/nextflow/src/test/groovy/nextflow/script/ScriptMetaTest.groovy:229]: Without `strict` mode it would cause a Stackoverflow right? If so I think the exception should be thrown in any case, irrespective of the strict mode

Comment (bentsherman) [reply modules/nextflow/src/test/groovy/nextflow/script/ScriptMetaTest.groovy:227]: Done, FYI the `validate()` function also checks for strict mode, although it shouldn't cause a stack overflow error, might be good to change for consistency

File: modules/nextflow/src/main/groovy/nextflow/script/ScriptMeta.groovy [hunk 2]
```diff
@@ -150,20 +150,11 @@ class ScriptMeta {
...
-                throw new DuplicateModuleFunctionException(msg)
-            log.warn(msg)
-        }
-        if (imports.get(name)) {
-            final msg = "A process with name '$name' is defined more than once in module script: $scriptPath -- Make sure to not define the same function as process"
-            if (NF.isStrictMode())
-                throw new DuplicateModuleFunctionException(msg)
-            log.warn(msg)
+        if( functionsCount.get(name) || imports.get(name) ) {
+            throw new DuplicateModuleFunctionException("A component (function, process, or workflow) named '$name' is defined more than once in module script: $scriptPath -- Make sure to not define multiple components with the same name")
```
Comment (pditommaso) [inline modules/nextflow/src/main/groovy/nextflow/script/ScriptMeta.groovy:157]: Was not better keeping separate branches to have a more precise error message?

Comment (bentsherman) [reply modules/nextflow/src/main/groovy/nextflow/script/ScriptMeta.groovy:157]: Well, they weren't precise to begin with. The branch tells you whether you are overwriting a function or an imported component (which could be function, process, or workflow). So if you wanted to be more precise, you would need to inspect the specific type of both `imports.get(name)` and `component` and produce an error message accordingly.

I thought about doing that, but seemed like overkill at the time

Comment (bentsherman) [reply modules/nextflow/src/main/groovy/nextflow/script/ScriptMeta.groovy:157]: I could e.g. implement a `getTypename()` method on each ComponentDef subclass and generate an error message from that

**Comment by bentsherman** [comment]
If you define two functions with the same name with different signatures, can they both be used or only the last definition? That will affect whether we should return an error or only a warning if the duplicates are both functions.

**Comment by bentsherman** [comment]
Did some testing, found that function overloading works the same as in Groovy as far as I can tell. If you define two functions with the same signatures, the Groovy compiler catches it before Nextflow. So `checkComponentName()` pertains mainly to checking for any duplicates introduced by module imports.

Since we changed it to always be an error, I had to remove a test that allows duplicate module imports.

Also, I think `ScriptMeta::validate()` is dead code. It checks for duplicate functions, but that should always be caught by `checkComponentName()` when the function is imported. I couldn't find a test case that triggered an error from `validate()`.

**Comment by pditommaso** [comment]
If I understand correctly, the exception is thrown irrespective of the strict flag, right?

**Comment by bentsherman** [comment]
Correct

**Comment by pditommaso** [comment]
Ok, update the PR title to reflect that
