### PR TITLE
Remove unnecessary runtime checks with strict syntax

### LINKED ISSUE #6533: "Process is already defined" error with nested subworkflows
### Expected behavior and actual behavior

When a subworkflow is used more than once in an workflow, and it is sometimes included from a different subworkflow, it raises the error
```
A process named '...' is already defined or included in script
```

### Steps to reproduce the problem

decompress [this MWE](https://github.com/user-attachments/files/23305873/mwe.zip)

Run 
```
NXF_SYNTAX_PARSER=v2 nextflow run .
```

### Program output 

```
 N E X T F L O W   ~  version 25.10.0

Launching `./main.nf` [boring_rutherford] DSL2 - revision: bb66e6056d

A process named 'PROCESS' is already defined or included in script: ./mwe/subworkflow.nf
```

### Environment 

* Nextflow version: 25.10.0 with NXF_SYNTAX_PARSER=v2
* Java version: 21.0.2
* Operating system: macOS
* Bash version: GNU bash, version 3.2.57(1)-release (arm64-apple-darwin25)

### Additional context

Note that if i move all the subworkflows to be defined in main.nf, instead of in separate files, the workflow runs successfully. Also, the error only occurs with `NXF_SYNTAX_PARSER=v2`

### PR DESCRIPTION
**Pull request by bentsherman**
Close #6533 

I haven't figured out exactly what causes this error, but I believe it is related to how the v2 parser loads scripts differently than the v1 parser

Since the v2 parser checks for conflicting declarations at compile-time, these runtime checks aren't needed anyway. Disabling these checks for the v2 parser allows the MWE to run successfully. There is already a unit test for this in `ScriptResolveTest`.

### CODE REVIEW

File: modules/nextflow/src/main/groovy/nextflow/script/parser/v2/ScriptLoaderV2.groovy [hunk 1]
```diff
@@ -156,7 +156,6 @@ class ScriptLoaderV2 implements ScriptLoader {
             final meta = ScriptMeta.get(script)
             meta.setScriptPath(path)
             meta.setModule(module)
-            meta.validate()
```
Comment (jorgee) [inline modules/nextflow/src/main/groovy/nextflow/script/parser/v2/ScriptLoaderV2.groovy:159]: Is it required to remove the validate()? I think only with the checkComponentName changes are enough. Or do you want to remove any validation at runtime for V2 parser?

Comment (bentsherman) [reply modules/nextflow/src/main/groovy/nextflow/script/parser/v2/ScriptLoaderV2.groovy:159]: One case checks for conflicting imports vs definitions in a module, while the other case checks for conflicting definitions in the same module. So I figure we might as well remove both since they are both handled at compile-time
