### PR TITLE
Fix incorrect AWS region when specifying a S3 regional endpoint

### LINKED ISSUE #6528: Nextflow redirects to us-east-1 when region endpoint is defined.
## Bug report 

When executing a pipeline with a configuration that defines an AWS region endpoint. Nextflow fallbacks to a global region default and pipeline execution fails with a malformed authorization header error.

```
$ nextflow run hello

 N E X T F L O W   ~  version 25.10.0

Launching `https://github.com/nextflow-io/hello` [pensive_brown] DSL2 - revision: 2ce0b0e294 [master]

ERROR ~ The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'eu-west-1' (Service: S3, Status Code: 400, Request ID: 0GR9TCB0WCACAJ9X, Extended Request ID: SSltf+NV3L+XjxJDbcmKlI71camPm51eFbo0AxyFZlc0ELRNcx8Z63u9HhHpsqvq662LXen67rcVa2GqMDgXwq7jRRgWRiOy) (SDK Attempt Count: 1)

 -- Check '.nextflow.log' file for details
```

### Expected behavior and actual behavior

It should correctly perform S3 calls using the `eu-west-1` endpoint and regions instead of falling back to global region `us-east-1`.  It is working with versions previous to the AWS SDK v2 change.

### Steps to reproduce the problem

Defines a nextflow config with a region endpoint and region:

```
aws.region = 'eu-west-1'
aws.client.endpoint = 'https://s3.eu-west-1.amazonaws.com'
```
and run any pipeline

`$ nextflow run hello`

### Environment 

* Nextflow version: [15.10.0] 
* Java version: [21]
* Operating system: [Linux]

### PR DESCRIPTION
**Pull request by jorgee**
close #6528 

This PR fixes a bug introduced when porting to AWS SDK v2. Nexflow sets the global region (US-EAST-1) when an amazon endpoint is defined, without checking if it is a regional endpoint. In AWS SDK v1, the s3 client didn't include a region when a endpoint was specified. However, the AWS SDK v2 S3 client require to define a region. It was resolved using the AwsS3Config.getS3GlobalRegion() that overwrites the region specified by the user if an amazon endpoint was specified, incorrectly assuming that endpoint refers to a global endpoint. 

This PR changes how the region is resolved when a endpoint is defined. First, it tries to get the region from the endpoint. If region in the endpoint, it tries to get from config or environment vars. Finally, fallback to us-east-1 if other options fail.

### CODE REVIEW

File: plugins/nf-amazon/src/main/nextflow/cloud/aws/config/AwsConfig.groovy [hunk 1]
```diff
@@ -93,10 +93,20 @@ class AwsConfig implements ConfigScope {
 
     AwsBatchConfig getBatchConfig() { batch }
 
-    String getS3GlobalRegion() {
-        return !region || !s3Config.endpoint || s3Config.endpoint.contains(".amazonaws.com")
-            ? Region.US_EAST_1.id()         // always use US_EAST_1 as global region for AWS endpoints
-            : region                        // for custom endpoint use the config provided region
```
Comment (pditommaso) [inline plugins/nf-amazon/src/main/nextflow/cloud/aws/config/AwsConfig.groovy:99]: Let's keep and mark deprecated

File: plugins/nf-amazon/src/main/nextflow/cloud/aws/config/AwsS3Config.groovy [hunk 2]
```diff
@@ -288,6 +289,35 @@ class AwsS3Config implements ConfigScope {
...
+     */
+    String getEndpointRegion(){
+        if( !endpoint || isCustomEndpoint() )
+            return null
+
+        try {
+            String host = URI.create(endpoint).getHost()
+            final hostDomains = host.split('\\.')
+            if (hostDomains.size() < 3) {
+                log.debug("Region subdomain doesn't exist.")
```
Comment (pditommaso) [inline plugins/nf-amazon/src/main/nextflow/cloud/aws/config/AwsS3Config.groovy]: Include `endpoint` in thee log message for troubleshooting

File: plugins/nf-amazon/src/main/nextflow/cloud/aws/config/AwsS3Config.groovy [hunk 3]
```diff
@@ -288,6 +289,35 @@ class AwsS3Config implements ConfigScope {
...
+                return null
+            }
+            final region = hostDomains[hostDomains.size()-3]
+            if (!Region.regions().contains(Region.of(region))){
```
Comment (pditommaso) [inline plugins/nf-amazon/src/main/nextflow/cloud/aws/config/AwsS3Config.groovy:309]: Include `endpoint` in the log message

File: plugins/nf-amazon/src/main/nextflow/cloud/aws/config/AwsS3Config.groovy [hunk 4]
```diff
@@ -288,6 +289,35 @@ class AwsS3Config implements ConfigScope {
...
+                log.debug("'${region}' is not a valid region.")
+                return null
+            }
+            return region
+
+        } catch (Exception e){
+            log.debug("Exception getting region from endpoint - ${e.message}")
```
Comment (pditommaso) [inline plugins/nf-amazon/src/main/nextflow/cloud/aws/config/AwsS3Config.groovy]:
```suggestion
            log.debug("Exception getting region from endpoint: '${endpoint}' - ${e.message}")
```

File: plugins/nf-amazon/src/main/nextflow/cloud/aws/config/AwsConfig.groovy (hunk 1 above)
Comment (jorgee) [reply plugins/nf-amazon/src/main/nextflow/cloud/aws/config/AwsConfig.groovy:99]: Done in ebbdf9583e2f107271ebed159c24613bec828dc7

File: plugins/nf-amazon/src/main/nextflow/cloud/aws/config/AwsS3Config.groovy (hunk 3 above)
Comment (jorgee) [reply plugins/nf-amazon/src/main/nextflow/cloud/aws/config/AwsS3Config.groovy:309]: Done in ebbdf9583e2f107271ebed159c24613bec828dc7

File: plugins/nf-amazon/src/main/nextflow/cloud/aws/config/AwsS3Config.groovy (hunk 2 above)
Comment (jorgee) [reply plugins/nf-amazon/src/main/nextflow/cloud/aws/config/AwsS3Config.groovy]: Done in ebbdf9583e2f107271ebed159c24613bec828dc7
