### PR TITLE
Fix Google Batch autoRetryExitCodes bug

### LINKED ISSUE #5827: Google Batch autoRetryExitCodes are not correctly set.
## Bug report 

The google.batch.autoRetryExitCodes set in the configuration it is not reflected in the Google Batch job description

### Expected behavior and actual behavior

When defining the google.batch.autoRetryExitCodes properties, they should appear in the Google Batch job description

### Steps to reproduce the problem

Set the following configuration
```
google {
    batch {
        autoRetryExitCodes = [50001, 50002, 50003, 50004, 50006]
        maxSpotAttempts = 5
    }
}
```
the look at the  job description
```
    lifecyclePolicies:
    - action: RETRY_TASK
      actionCondition:
        exitCodes:
        - 50001
    maxRetryCount: 5
```
The only exit code that is appearing is the default 50001.

### Environment 

* Nextflow version: 25.01-edge 
* Java version: 21
* Operating system: Linux

### PR DESCRIPTION
**Pull request by jorgee**
close #5827 

The autoretry exit code set in the google Batch Job request was hardcoded to the default value. This branch fixes it, setting the codes specified in the configuration.

### CODE REVIEW

File: plugins/nf-google/src/main/nextflow/cloud/google/batch/GoogleBatchTaskHandler.groovy [hunk 1]
```diff
@@ -17,6 +17,8 @@
 
 package nextflow.cloud.google.batch
 
+import nextflow.cloud.google.batch.client.BatchConfig
+
```
Comment (bentsherman) [inline plugins/nf-google/src/main/nextflow/cloud/google/batch/GoogleBatchTaskHandler.groovy:21]:
```suggestion
```

**Review by pditommaso — APPROVED** [review]
