### PR TITLE
Handle Azure Batch ActiveJobAndScheduleQuotaReached with retry

### LINKED ISSUE #5575: Wait for Azure Batch job quota to clear before submitting a new job
## New feature

Occasionally, you can hit the Azure Batch job limit when running a pipeline, leading to this error:

```
Error executing process > 'NFCORE_VIRALRECON:ILLUMINA:VARIANTS_IVAR:IVAR_VARIANTS_TO_VCF (SAMPLE2_PE)'

Caused by:
  Status code 409, "{
    "odata.metadata":"https://name.region.batch.azure.com/$metadata#Microsoft.Azure.Batch.Protocol.Entities.Container.errors/@Element","code":"ActiveJobAndScheduleQuotaReached","message":{
      "lang":"en-US","value":"Active job and job schedule quota for the account has been reached.\nRequestId:d28008e3-4018-41cc-90ff-6d96a7952ea3\nTime:2024-12-05T02:43:12.5743776Z"
    }
  }"
```

We could catch this error and just wait for the job quota to clear. This could be configurable as an `azure.batch` config option.

## Usage scenario 

Set `azure.batch.behaviourOnJobLimit = 'retry'` and Azure will retry with a backoff until cancelled. Alternatively, set it to `error` and it will do the current behaviour and raise an error.

Raise a warning to the console so the user is aware.

This would allow pipelines to continue, albeit stuck in a queue. As jobs are cleared, the pipelines will continue.

## Suggest implementation 

tbc

Related: https://github.com/nextflow-io/nextflow/issues/4792

### PR DESCRIPTION
**Pull request by adamrtalbot**
## Summary

Fixes #5575

When Azure Batch hits the active job and schedule quota (HTTP 409 `ActiveJobAndScheduleQuotaReached`), Nextflow now retries with configurable backoff instead of failing immediately.

## Changes

- **`AzBatchService.groovy`**: Added `applyCreateJob()` using Failsafe `RetryPolicy` with a fixed delay to handle `ActiveJobAndScheduleQuotaReached` quota errors. This layers on top of the existing `apply()` method — `apply()` handles short-lived transient errors (408, 429, 500, etc.) while `applyCreateJob()` handles the longer-lived quota exhaustion with configurable fixed delays. Extracted `createJobRequest()` and `isJobQuotaError()` as protected methods for testability.
- **`AzBatchOpts.groovy`**: Added two new config options:
  - `azure.batch.maxJobQuotaRetries` (int, default `3`) — maximum number of retries when quota is reached
  - `azure.batch.jobQuotaRetryDelay` (Duration, default `2 min`) — delay between retries
- **`AzBatchServiceTest.groovy`**: Added 6 unit tests covering: success on first try, retry then succeed, exhaust retries, zero retries, non-quota 409 errors, and non-HTTP exceptions.

## Behavior

When job creation fails with `ActiveJobAndScheduleQuotaReached`:
1. A warning is logged: `Azure Batch active job quota reached - waiting 2m before retry (attempt 1 of 3)`
2. Failsafe waits for the configured delay
3. Job creation is retried
4. If retries are exhausted, an `IllegalStateException` is thrown with a helpful message suggesting config changes

### CODE REVIEW

File: plugins/nf-azure/src/main/nextflow/cloud/azure/batch/AzBatchService.groovy [hunk 1]
```diff
@@ -450,11 +450,46 @@ class AzBatchService implements Closeable {
...
+                    log.warn "Azure Batch active job quota reached - waiting ${retryDelay} before retry (attempt ${attempt + 1} of ${maxRetries})"
+                    sleep(retryDelay.toMillis())
+                }
+                else {
+                    throw e
+                }
+            }
+        }
+    }
+
```
Comment (pditommaso) [inline plugins/nf-azure/src/main/nextflow/cloud/azure/batch/AzBatchService.groovy]: How this improve vs `apply(() -> client.createJob(content))`

Comment (adamrtalbot) [reply plugins/nf-azure/src/main/nextflow/cloud/azure/batch/AzBatchService.groovy]: `apply()` uses Failsafe to retry on transient HTTP errors (`RETRY_CODES = [408, 429, 500, 502, 503, 504]`), IOExceptions, and TimeoutExceptions. It does **not** retry on 409 — correctly, since most 409 Conflict errors shouldn't be retried.

However, `ActiveJobAndScheduleQuotaReached` is a specific 409 that **is** transient — the quota frees up as existing jobs complete. It needs a different retry strategy than `apply()` provides:

- **Longer delays** — minutes not seconds, since jobs take time to finish
- **Fewer retries** — with 2-minute delays, we don't want dozens of attempts
- **User-visible warning** — so users know they're hitting the quota limit and can adjust config

Note that `createJobRequest()` still calls `apply()` internally, so both layers are active: `apply()` handles short-lived transient errors, while `safeCreateJob()` handles the longer-lived quota exhaustion on top.

Comment (adamrtalbot) [reply plugins/nf-azure/src/main/nextflow/cloud/azure/batch/AzBatchService.groovy]: `apply()` handles transient errors (e.g. 429, 50*). A quota error will recover but requires a longer wait.

A 409 means there are too many Jobs & Tasks running, which means you should hold off before submitting more. This means the correct response isn't a quick retry via the standard Azure API error strategy, but a more realistic backoff. Not in 30 seconds but in minutes, perhaps hours. I've been conservative here, but it's reasonable to increase the timeout to a whole day if you are running at very high throughput.

Note `safeCreateJob` uses `apply()` internally, so both layers are active.

Comment (adamrtalbot) [reply plugins/nf-azure/src/main/nextflow/cloud/azure/batch/AzBatchService.groovy]: Also, adding 409 to [the accepted error codes](https://github.com/nextflow-io/nextflow/blob/fix/azure-batch-scratch/plugins/nf-azure/src/main/nextflow/cloud/azure/batch/AzBatchService.groovy#L1083-L1084) will mean we treat other 409s the same as job submission. E.g. a "pool already exists" error will be handled with the same backoff retry strategy as reaching the job quota limit which is invalid behaviour.

Comment (pditommaso) [reply plugins/nf-azure/src/main/nextflow/cloud/azure/batch/AzBatchService.groovy]: You have full control on the retry logic extending that one or using a variation

Comment (pditommaso) [reply plugins/nf-azure/src/main/nextflow/cloud/azure/batch/AzBatchService.groovy]: Sorted
