### PR TITLE
Retry Google 500 errors when writing task helper files

### LINKED ISSUE #4537: google-batch workflow interruptions with "UNAVAILABLE: 502:Bad Gateway"
## Bug report 

When running workflows with google-batch, I sometimes get an `UNAVAILABLE: 502:Bad Gateway` error which causes a workflow to be interrupted regardless of my error strategy. This is relatively rare, seemingly random, and happens mostly for large runs (usually thousands of jobs). The issue might also not be linked to nextflow itself but the google-batch service.
Finally, it's probably not related, but for the specific run I shared below, I had many jobs that were preempted (~800 among over ~6k submitted jobs).

### Expected behavior and actual behavior

Expected: Normal execution of the workflow or more feedback about what the actual issue is.
Actual: Workflow interrupted

### Steps to reproduce the problem

Unable to reproduce, but happens fairly consistently for large scale runs (custom RNA-seq pipeline)

### Program output 
See attached [.nextflow.log
](https://github.com/nextflow-io/nextflow/files/13444648/bad_gateway_nextflow.log)

Relevant lines:
```
Nov-20 18:27:15.840 [Task submitter] DEBUG nextflow.processor.TaskProcessor - Handling unexpected condition for
  task: name=ROME_QUANT_HS:FASTQ_FILTER (PPMI-Phase1-IR1.51625.BL.0000430667.5104-SL-0473.L002); work-dir=gs://nxf-work/cedric/ROMEQuant/4b/98813e83210abb7fcba3c9c5261e40
  error [com.google.api.gax.rpc.UnavailableException]: io.grpc.StatusRuntimeException: UNAVAILABLE: 502:Bad Gateway
Nov-20 18:27:15.857 [Task submitter] ERROR nextflow.processor.TaskProcessor - Error executing process > 'ROME_QUANT_HS:FASTQ_FILTER (PPMI-Phase1-IR1.51625.BL.0000430667.5104-SL-0473.L002)'

Caused by:
  UNAVAILABLE: 502:Bad Gateway

com.google.api.gax.rpc.UnavailableException: io.grpc.StatusRuntimeException: UNAVAILABLE: 502:Bad Gateway
        at com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:112)
        at com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:41)
        at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:86)
        at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:66)
        at com.google.api.gax.grpc.GrpcExceptionCallable$ExceptionTransformingFuture.onFailure(GrpcExceptionCallable.java:97)
        at com.google.api.core.ApiFutures$1.onFailure(ApiFutures.java:67)
        at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1132)
        at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:31)
        at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1270)
        at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:1038)
        at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:808)
        at io.grpc.stub.ClientCalls$GrpcFuture.setException(ClientCalls.java:574)
        at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:544)
        at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
        at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
        at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
        at com.google.api.gax.grpc.ChannelPool$ReleasingClientCall$1.onClose(ChannelPool.java:541)
        at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:576)
        at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:70)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:757)
--
                at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
                at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
                at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1254)
                at groovy.lang.MetaClassImpl.invokeMethodClosure(MetaClassImpl.java:1042)
                at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1128)
                at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1030)
                at groovy.lang.Closure.call(Closure.java:427)
                at groovy.lang.Closure.call(Closure.java:406)
                at groovy.lang.Closure.run(Closure.java:498)
                ... 1 common frames omitted
Caused by: io.grpc.StatusRuntimeException: UNAVAILABLE: 502:Bad Gateway
        at io.grpc.Status.asRuntimeException(Status.java:539)
        ... 14 common frames omitted
Nov-20 18:27:15.866 [Task submitter] DEBUG nextflow.Session - Session aborted -- Cause: io.grpc.StatusRuntimeException: UNAVAILABLE: 502:Bad Gateway
```

### Environment 

* Nextflow version: `23.09.3-edge build 5888`
* Java version: `openjdk version "11.0.20.1" 2023-08-24`
* Operating system: `Linux nf-tower-main 5.15.0-1027-gcp #34~20.04.1-Ubuntu SMP Mon Jan 9 18:40:09 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`
* Bash version: `zsh 5.8 (x86_64-ubuntu-linux-gnu)`

### PR DESCRIPTION
**Pull request by bentsherman**
Close #4537 

HTTP response exceptions from the Google SDK are IOExceptions: https://cloud.google.com/java/docs/reference/google-http-client/latest/com.google.api.client.http.HttpResponseException

### CODE REVIEW

File: modules/nextflow/src/main/groovy/nextflow/executor/BashWrapperBuilder.groovy [hunk 1]
```diff
@@ -449,7 +449,7 @@ class BashWrapperBuilder {
                 }
                 return path
             }
-            catch (FileSystemException | SocketException | RuntimeException e) {
+            catch (FileSystemException | IOException | RuntimeException | SocketException e) {
```
Comment (pditommaso) [inline modules/nextflow/src/main/groovy/nextflow/executor/BashWrapperBuilder.groovy:452]: The problem is IOException is very generic, even if the path is wrong it will enter in a retry loop

Comment (bentsherman) [reply modules/nextflow/src/main/groovy/nextflow/executor/BashWrapperBuilder.groovy:452]: Oof, then we need to handle this at the level of the GCS filesystem. We might need to implement a wrapper around the NIO filesystem provided by the google SDK...

Comment (bentsherman) [reply modules/nextflow/src/main/groovy/nextflow/executor/BashWrapperBuilder.groovy:452]: Fortunately I have done most of that in [this branch](https://github.com/nextflow-io/nextflow/tree/3372-google-nio-filesystem), if we want to go down that route

Comment (pditommaso) [reply modules/nextflow/src/main/groovy/nextflow/executor/BashWrapperBuilder.groovy:452]: A simple hack could be to check the class name (or simple name) as a string

Comment (pditommaso) [reply modules/nextflow/src/main/groovy/nextflow/executor/BashWrapperBuilder.groovy:452]: @bentsherman any clue whats the google base class name for those errors?

Comment (bentsherman) [reply modules/nextflow/src/main/groovy/nextflow/executor/BashWrapperBuilder.groovy]: it directly extends IOException so your solution is the best we can do without adding google deps

File: modules/nextflow/src/main/groovy/nextflow/executor/BashWrapperBuilder.groovy [hunk 2]
```diff
@@ -463,6 +465,18 @@ class BashWrapperBuilder {
...
     }
 
+    static protected boolean isRetryable0(Exception e) {
+        if( e instanceof FileSystemException )
+            return true
+        if( e instanceof SocketException )
+            return true
+        if( e instanceof RuntimeException )
+            return true
+        if( e.class.getSimpleName() == 'HttpResponseException' )
```
Comment (bentsherman) [inline modules/nextflow/src/main/groovy/nextflow/executor/BashWrapperBuilder.groovy:475]:
```suggestion
        if( e.class.getName() == 'com.google.api.client.http.HttpResponseException' )
```

Comment (pditommaso) [reply modules/nextflow/src/main/groovy/nextflow/executor/BashWrapperBuilder.groovy:475]: Actually, I did `HttpResponseException` on purpose. The logic is that any http prefixed class name is eligible for retry

Comment (bentsherman) [reply modules/nextflow/src/main/groovy/nextflow/executor/BashWrapperBuilder.groovy:475]: okay 🤞
