### PR TITLE
Revert Plugins.init() at run command to original location

### LINKED ISSUE #6566: nf-amazon plugin not available for latest 25.10.0 release
### Expected behavior and actual behavior

When passing an s3 path for the `-params-file` parameter, I'd expect nextflow to use nf-amazon plugin to get it. This works with version 25.04.8 but not in 25.10.0 anymore.

### Steps to reproduce the problem

```{bash}
nextflow run https://github.com/seqeralabs/nf-hello-world -params-file s3://example_bucket/hello/params.json
```

### Program output 

```
 N E X T F L O W   ~  version 25.10.0

WARN: Unable to start plugin 'nf-amazon' required by s3://example_bucket/hello/params.json
ERROR ~ Missing plugin 'nf-amazon' required to read file: s3://example_bucket/hello/params.json

 -- Check '.nextflow.log' file for details
```
> I get the same error even if I use an actual s3 path so the path itself doesn't matter....

### Environment 

* Nextflow version: 25.10.0 
* Java version: openjdk version "17.0.6" 2023-01-17 LTS
* Operating system: macOS
* Bash version: zsh 5.9 (arm64-apple-darwin24.0)

### Additional context

If I downgrade to nextflow version `25.04.8` then it works correctly (with the above command it then complains that the s3 path doesn't exist but thats a valid error)

### PR DESCRIPTION
**Pull request by jorgee**
close #6566 

Commit 9e4c975 moved the Plugins.init() later in the code- Plugins.init() initializes the plugins manager, so autoStartIfMissing call done  before loading the configuration will fail. It includes getting the Repository providers implemented in plugins or downloading remote param-files. 

This PR moves again the Plugins.init() to begining of run command. This change doesn't affect secrets loading (tested in platform with `bentsherman/nf-tests -r plugin-secrets`). The first time that the config is loaded, it uses the EmptySecretsProvider, it doesn't affect if a plugin has been loaded before.

### CODE REVIEW

**Comment by bentsherman** [comment]
Before we do this, I would like to understand why the params-file can be an S3 path but not an Azure path

It doesn't seem like either of these use cases were ever intentionally supported, considering that the params file is loaded before the config, which means the params file shouldn't be able to access remote storage

**Comment by bentsherman** [comment]
It never worked for google storage either: #5390

**Comment by jorgee** [comment]
The difference is in the path factory. For S3, nextflow gets the config from Global.config. For Google and Azure, it gets from Global.session.config, and they return a exception if session is null. At the point of loading the params with S3, the Global.config is null, but as it is not failing, it just create an empty Map and works with the env vars, sso, instace role, or whatever is configured in the process running the run command.  

We can do the same for the other cases and it will work. However, I see a side effect for S3 and Azure. File systems are storing the client used to access the cloud storage. In these cases, file systems are set per bucket and there is a hashmap to cache file systems based on bucket name. So, if there are specific configurations in the nextflow config file for the bucket used in the params file, they will never be applied. It will not happen in Google because the key file system cache map includes the configuration.

**Comment by pditommaso** [comment]
Quick patch for 25.10.1 and separate task trying to have a common approach to this problem?

File: modules/nextflow/src/main/groovy/nextflow/cli/CmdRun.groovy [hunk 1]
```diff
@@ -324,6 +324,7 @@ class CmdRun extends CmdBase implements HubOptions {
         printBanner()
 
         // -- resolve main script
+        Plugins.init()
```
Comment (bentsherman) [inline modules/nextflow/src/main/groovy/nextflow/cli/CmdRun.groovy:326]:
```suggestion
        Plugins.init()

        // -- resolve main script
```
