### PR TITLE
initialize the plugin once it's defined

### LINKED ISSUE #3348: plugin init method is not called if only contains functions
## Bug report 

Calling a function in a plugin without operators defined produces a NullPointerException 

### Environment 

* Nextflow version: 2.10.0

### PR DESCRIPTION
**Pull request by jorgeaguileraseqera**
Currently, nextflow is calling the `init` method of the plugin in the first call of the Operator

This PR initializes the plugin once it's defined 

closes #3348

### CODE REVIEW

File: modules/nextflow/src/main/groovy/nextflow/plugin/extension/PluginExtensionProvider.groovy [hunk 1]
```diff
@@ -153,6 +153,7 @@ class PluginExtensionProvider implements ExtensionProvider {
                 throw new IllegalStateException("Extension '$realName' it isn't defined by plugin ${pluginId}")
             }
         }
+        ext.checkInit((Session)Global.session)
```
Comment (pditommaso) [inline modules/nextflow/src/main/groovy/nextflow/plugin/extension/PluginExtensionProvider.groovy:156]:
```suggestion
        // initialise the plugin session 
        ext.checkInit((Session)Global.session)
```

**Review by pditommaso — APPROVED** [review]
