### PR TITLE
Fix for nested params with the same name

### LINKED ISSUE #1982: Nested params in different scopes overwrite each other
### Expected behavior and actual behavior

When defining nested params in the curly brackets notation, a nested param in a different scope will overwrite ones found before, if they have a similar path.

For example, If I have a `nextflow.config` file:

```nextflow
params {
  foo {
    bar = 'bar1'
  }
  baz = 'baz1'
  nested {
    baz = 'baz2'
    foo {
      bar = 'bar2'
    }
  }
}
```

**Expected:** I can print out the `config` and see the same thing that I passed in.

**Actual:** When I print out the `config`, I see that `nested.foo.bar` has overwritten `foo.bar` to be `'bar2'`.

#### Files

**`test1.config`**:

```nextflow
params {
  foo {
    bar = 'bar1'
  }
  baz = 'baz1'
  nested {
    baz = 'baz2'
    foo {
      bar = 'bar2'
    }
  }
}
```

**`printparams.nf`**:

```nextflow
log.info "$params"
```

#### Command

These two commands show the same result in different formats:

```
NXF_VER="21.03.0-edge" nextflow -C test1.config config
```

```
NXF_VER="21.03.0-edge" nextflow -C test1.config run printparams.nf
```

### Program output 

From `config` command:

```
params {
   foo {
      bar = 'bar2'
   }
   baz = 'baz1'
   nested {
      baz = 'baz2'
      foo {
         bar = 'bar2'
      }
   }
}
```

From `printparams.nf`:

```
N E X T F L O W  ~  version 21.03.0-edge
Launching `printparams.nf` [sad_saha] - revision: 4d4685b5b4
[foo:[bar:bar2], baz:baz1, nested:[baz:baz2, foo:[bar:bar2]]]
```

### Environment 

* Nextflow version: `21.03.0-edge` 
* Java version: `openjdk version "1.8.0_232"`
* Operating system: macOS
* Bash version: `zsh 5.8 (x86_64-apple-darwin20.0)`

### Additional context

Above, using `test1.config`, (**Example 1**), we see that `nested.foo.bar` overwrites `foo.bar`. here are more examples:

#### Example 2

Here, `nested2.foo.bar` overwrites `nested.foo.bar` and `foo.bar`

test2.config:
```nextflow                    
params {
  foo {
    bar = 'bar1'
  }
  baz = 'baz1'
  nested {
    baz = 'baz2'
    foo {
      bar = 'bar2'
    }
  }
  bar = 'bar3'
  nested2 {
    baz = 'baz3'
    foo {
      bar = 'bar4'
    }
  }
}
```
```
❯ NXF_VER="21.03.0-edge" nextflow -C test2.config config
params {
   foo {
      bar = 'bar4'
   }
   baz = 'baz1'
   nested {
      baz = 'baz2'
      foo {
         bar = 'bar4'
      }
   }
   bar = 'bar3'
   nested2 {
      baz = 'baz3'
      foo {
         bar = 'bar4'
      }
   }
}
```

#### Example 3

If I list the shallowest scope last, there is no overriding:

test3.config:
```nextflow
params {
  baz = 'baz1'
  nested {
    baz = 'baz2'
    foo {
      bar = 'bar2'
    }
  }
  bar = 'bar3'
  nested2 {
    baz = 'baz3'
    foo {
      bar = 'bar4'
    }
  }
  foo {
    bar = 'bar1'
  }
}
```
```
❯ NXF_VER="21.03.0-edge" nextflow -C test3.config config
params {
   baz = 'baz1'
   nested {
      baz = 'baz2'
      foo {
         bar = 'bar2'
      }
   }
   bar = 'bar3'
   nested2 {
      baz = 'baz3'
      foo {
         bar = 'bar4'
      }
   }
   foo {
      bar = 'bar1'
   }
}
```

#### Example 4

If I use dot-notation, there is also no unwanted overwriting:

test4.config (equal information as test1.config, different format):
```nextflow
params.foo.bar = 'bar1'
params.baz = 'baz1'
params.nested.baz = 'baz2'
params.nested.foo.bar = 'bar2'
```
```
❯ NXF_VER="21.03.0-edge" nextflow -C test4.config config
params {
   foo {
      bar = 'bar1'
   }
   baz = 'baz1'
   nested {
      baz = 'baz2'
      foo {
         bar = 'bar2'
      }
   }
}
```

### PR DESCRIPTION
**Pull request by jacarey**
This fixes #1982, #2166, #2247 and #2358

The first three issues were caused by a lack of cloning which allowed mutability of values where they should have been immutable.  

The last issue required a deep merge vs a `putAll` to avoid overwriting multiple values at the same level when you are overriding them on the command line.

### CODE REVIEW

File: modules/nextflow/src/test/groovy/nextflow/config/ConfigParserTest.groovy [hunk 1]
```diff
@@ -617,6 +617,32 @@ class ConfigParserTest extends Specification {
         folder?.deleteDir()
     }
 
+    def 'should not overwrite param values with nested values of with the same name' () {
```
Comment (nh13) [inline modules/nextflow/src/test/groovy/nextflow/config/ConfigParserTest.groovy:620]:
```suggestion
    def 'should not overwrite param values with nested values with the same name' () {
```

**Review by nh13 — APPROVED** [review]

**Review by pditommaso — CHANGES_REQUESTED** [review]
Awesome patch, this was really tricky! 

Find attached a patch to fix also a failing test, plus one more test to check the dotted notation of the same snippet 


[patch.txt](https://github.com/nextflow-io/nextflow/files/7677126/patch.txt)

**Review by pditommaso — APPROVED** [review]
Awesome, thanks

**Comment by pditommaso** [comment]
Release along with version 21.12.1-edge
