### PR TITLE
Fix K8s token refresh by caching K8sClient at executor level

### LINKED ISSUE #6918: K8s executor caches client token at wrong layer — PR #6742 token refresh never triggered
## Summary

PR #6742 added time-based cache refresh (50min default) to `K8sConfig.getClient()` to handle projected SA token rotation on Kubernetes. However, `K8sExecutor` creates a `K8sClient` once from the `ClientConfig` and caches it in a private field. `K8sExecutor.getClient()` returns this cached instance directly — it never calls `K8sConfig.getClient()` again, so the Guava cache refresh is never triggered.

### The caching chain

```
K8sConfig.getClient()       → Guava cache, 50min expiry (PR #6742 fix) ✅
  ↓ called once
K8sExecutor.client          → K8sClient created ONCE, stored in private field ❌
K8sExecutor.getClient()     → returns this.client (never re-calls K8sConfig) ❌
  ↓
K8sTaskHandler.client       → set to executor.getClient() in constructor ❌
  ↓
client.podState()/podDelete() → uses stale token forever ❌
```

### Reproduction

- Any Kubernetes cluster with projected SA tokens (`expirationSeconds: 3607`, ~1hr default on AKS, RKE2, etc.)
- Run any pipeline that takes **>1 hour**
- Nextflow 26.02.0-edge with nf-k8s 1.5.0
- After ~60 minutes: `401 Unauthorized` on `GET /api/v1/namespaces/{ns}/pods/{name}/status`

### Error

```
Caused by:
  Request GET /api/v1/namespaces/seqera-nf/pods/nf-xxx/status returned an error code=401
  {"kind":"Status","apiVersion":"v1","status":"Failure","message":"Unauthorized","reason":"Unauthorized","code":401}
```

### Expected behavior

Token should be re-read from disk periodically. The kubelet rotates projected tokens at ~80% of their lifetime (~48min for the default 3607s). The Guava cache in `K8sConfig` correctly expires at 50min, but it is never reached because `K8sExecutor` caches the `K8sClient` object at a higher layer.

### Suggested fix

The refresh logic needs to be at the `K8sExecutor.getClient()` level (or `K8sClient` should re-read the token from disk), not just at `K8sConfig.getClient()`. Either:

1. `K8sExecutor.getClient()` should call `K8sConfig.getClient()` on each invocation (and let the Guava cache handle deduplication), or
2. `K8sClient` should re-read the token file from disk on 401 responses (adding 401 to `RETRY_CODES` with a token refresh step)

### Regression note

This is a **regression** from older nf-k8s versions. nf-k8s **1.2.2** (Nextflow 25.10.4) works fine past 1 hour on the same infrastructure — the client was not cached at the executor level in that version.

### Environment

- Nextflow: 26.02.0-edge (build 11371, 2026-02-28)
- nf-k8s plugin: 1.5.0
- Kubernetes: AKS 1.27.7
- Seqera Platform: cloud.seqera.io
- Related: #6741, #6742

### PR DESCRIPTION
**Pull request by pditommaso**
## Summary

Fixes #6918 — supersedes #6920

### Problem

PR #6742 added a Guava cache to `K8sConfig.getClient()` with a 50-minute expiry to refresh the service account token. However, the cache was never consulted after startup because:

- `K8sExecutor.register()` called `k8sConfig.getClient()` once and stored the result in a private `K8sClient` field
- `K8sExecutor.getClient()` returned that stored field directly
- `K8sTaskHandler` stored `executor.client` in its constructor, bypassing `getClient()` entirely

This caused **401 Unauthorized errors after ~60 minutes** on clusters with short-lived projected service account tokens (e.g. AKS, RKE2).

### Why not #6920

PR #6920 correctly identified the root cause but had two issues:

1. **Created a new `K8sClient` on every `getClient()` call** — the Guava cache in `K8sConfig` only cached `ClientConfig`, so every poll/submit/delete call triggered `new K8sClient(...)` which re-parses SSL certificates and initializes the trust manager
2. **Cache at the wrong level** — `K8sConfig` is a configuration object; the client lifecycle belongs in the executor

### Fix

- **Move the Guava cache from `K8sConfig` to `K8sExecutor`** — cache the `K8sClient` itself (not just `ClientConfig`), avoiding redundant SSL setup on every API call
- `K8sConfig.getClient()` becomes a plain factory method that creates a fresh `ClientConfig` (re-reading the token from disk)
- `K8sTaskHandler` uses `executor.getClient()` instead of direct field access
- Added `K8sExecutorTest` covering cache hit and expiration behavior

### CODE REVIEW

File: plugins/nf-k8s/src/main/nextflow/k8s/K8sExecutor.groovy [hunk 1]
```diff
@@ -41,12 +45,17 @@ import org.pf4j.ExtensionPoint
...
-    private K8sClient client
+    private Cache<String, K8sClient> clientCache
 
+    /**
+     * @return The Kubernetes HTTP client. Delegates to a Guava cache that refreshes
+     * the client (including the service account token) when the configured interval expires.
+     */
     protected K8sClient getClient() {
-        client
+        clientCache.get('client', () -> new K8sClient(k8sConfig.getClient()))
```
Comment (adamrtalbot) [inline plugins/nf-k8s/src/main/nextflow/k8s/K8sExecutor.groovy:58]: Took me a sec to get this, so I'll leave a comment here for future readers. The client config (including token) is cached, but the k8s client itself is recreated on every submit task. This means on a new client is created every time but it's very lightweight. While building a client, it will use the config which is refreshed every 50 minutes (default value).

This is all handled by `getClient()` reaches into the Guava cache instead of getting a fresh client. Guava cache handles use-or-get logic.
